id = "shhhed-theme"
name = "shhhed"
version = "0.0.1"
schema_version = 1
authors = ["mkhamat"]
description = "A dark, muted theme with soft greens and purples"
repository = "https://github.com/mkhamat/shhhed"
