id = "shhhed-theme"
name = "shhhed"
version = "1.52.0"
schema_version = 1
authors = ["mkhamat"]
description = "🤫 Theme that dims the scaffolding and colors what matters. Dark and light."
repository = "https://github.com/mkhamat/shhhed"
